config/routes.rb
Rails.application.routes.draw do
  resources :cookbook_ingredients
  resources :cookbooks
  resources :ingredients
  get 'welcome/index'
 
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
	has_many :cookbook_ingredients
	has_many :ingredients, :through => :cookbook_ingredients
end

app/models/cookbook_ingredient.rb
class CookbookIngredient < ApplicationRecord
	belongs_to :cookbook
	belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :cookbook_ingredients
	has_many :cookbooks, :through => :cookbook_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cookbook_ingredients_controller.rb
class CookbookIngredientsController < ApplicationController
  before_action :set_cookbook_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /cookbook_ingredients
  # GET /cookbook_ingredients.json
  def index
    @cookbook_ingredients = CookbookIngredient.all
  end

  # GET /cookbook_ingredients/1
  # GET /cookbook_ingredients/1.json
  def show
  end

  # GET /cookbook_ingredients/new
  def new
    @cookbook_ingredient = CookbookIngredient.new
  end

  # GET /cookbook_ingredients/1/edit
  def edit
  end

  # POST /cookbook_ingredients
  # POST /cookbook_ingredients.json
  def create
    @cookbook_ingredient = CookbookIngredient.new(cookbook_ingredient_params)

    respond_to do |format|
      if @cookbook_ingredient.save
        format.html { redirect_to @cookbook_ingredient, notice: 'Cookbook ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @cookbook_ingredient }
      else
        format.html { render :new }
        format.json { render json: @cookbook_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbook_ingredients/1
  # PATCH/PUT /cookbook_ingredients/1.json
  def update
    respond_to do |format|
      if @cookbook_ingredient.update(cookbook_ingredient_params)
        format.html { redirect_to @cookbook_ingredient, notice: 'Cookbook ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @cookbook_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @cookbook_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbook_ingredients/1
  # DELETE /cookbook_ingredients/1.json
  def destroy
    @cookbook_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to cookbook_ingredients_url, notice: 'Cookbook ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook_ingredient
      @cookbook_ingredient = CookbookIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_ingredient_params
      params.require(:cookbook_ingredient).permit(:cookbook_id, :ingredient_id)
    end
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
  end

  # GET /cookbooks/new
  def new
    @cookbook = Cookbook.new
  end

  # GET /cookbooks/1/edit
  def edit
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(cookbook_params)

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render :show, status: :created, location: @cookbook }
      else
        format.html { render :new }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbooks/1
  # PATCH/PUT /cookbooks/1.json
  def update
    respond_to do |format|
      if @cookbook.update(cookbook_params)
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @cookbook }
      else
        format.html { render :edit }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook.destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_url, notice: 'Cookbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_params
      params.require(:cookbook).permit(:name, :description, :text, :time, :int, :serving)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :unit)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookbook_ingredients_helper.rb
module CookbookIngredientsHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cookbook_ingredients/_form.html.erb
<%= form_with(model: cookbook_ingredient, local: true) do |form| %>
  <% if cookbook_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cookbook_ingredient.errors.count, "error") %> prohibited this cookbook_ingredient from being saved:</h2>

      <ul>
      <% cookbook_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
    <%= form.label :cookbook_id %>
    <%= form.collection_select :cookbook_id, Cookbook.order(:id),:id,:name, include_blank: true %>
  </div>
   

  <div class="field">
    <%= form.label :ingredient_id %>
    <%= form.collection_select :ingredient_id, Ingredient.order(:id),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :cookbook_ingredient_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cookbook_ingredients/edit.html.erb
<h1>Editing Cookbook Ingredient</h1>

<%= render 'form', cookbook_ingredient: @cookbook_ingredient %>

<%= link_to 'Show', @cookbook_ingredient %> |
<%= link_to 'Back', cookbook_ingredients_path %>

app/views/cookbook_ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cookbook Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Cookbook</th>
      <th>Cookbook Name</th>
      <th>Ingredient</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cookbook_ingredients.each do |cookbook_ingredient| %>
      <tr>
        <td><%= cookbook_ingredient.cookbook_id %></td>
        <td><%= cookbook_ingredient.cookbook.name %></td>
        <td><%= cookbook_ingredient.ingredient_id %></td>
        <td><%= cookbook_ingredient.ingredient.name %></td>
        <td><%= cookbook_ingredient.quantity %></td>
        <td><%= cookbook_ingredient.ingredient.unit %></td>
        <td><%= link_to 'Show', cookbook_ingredient %></td>
        <td><%= link_to 'Edit', edit_cookbook_ingredient_path(cookbook_ingredient) %></td>
        <td><%= link_to 'Destroy', cookbook_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookbook Ingredient', new_cookbook_ingredient_path %>

app/views/cookbook_ingredients/new.html.erb
<h1>New Cookbook Ingredient</h1>

<%= render 'form', cookbook_ingredient: @cookbook_ingredient %>

<%= link_to 'Back', cookbook_ingredients_path %>

app/views/cookbook_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cookbook:</strong>
  <%= @cookbook_ingredient.cookbook_id %>
</p>

<p>
  <strong>Cookbook Name:</strong>
  <%= @cookbook_ingredient.cookbook.name %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @cookbook_ingredient.ingredient_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cookbook_ingredient.ingredient.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cookbook_ingredient.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @cookbook_ingredient.ingredient.unit %>
</p>

<%= link_to 'Edit', edit_cookbook_ingredient_path(@cookbook_ingredient) %> |
<%= link_to 'Back', cookbook_ingredients_path %>

app/views/cookbooks/_form.html.erb
<%= form_with(model: cookbook, local: true) do |form| %>
  <% if cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% cookbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cookbook_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :cookbook_description %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :cookbook_time %>
  </div>

  <div class="field">
    <%= form.label :serving %>
    <%= form.text_field :serving, id: :cookbook_serving %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing Cookbook</h1>

<%= render 'form', cookbook: @cookbook %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cookbooks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Time</th>
      <th>Serving</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cookbooks.each do |cookbook| %>
      <tr>
        <td><%= cookbook.name %></td>
        <td><%= cookbook.description %></td>
        <td><%= cookbook.time %></td>
        <td><%= cookbook.serving %></td>
        <td><%= link_to 'Show', cookbook %></td>
        <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
        <td><%= link_to 'Destroy', cookbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookbook', new_cookbook_path %>

app/views/cookbooks/new.html.erb
<h1>New Cookbook</h1>

<%= render 'form', cookbook: @cookbook %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cookbook.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cookbook.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @cookbook.time %>
</p>

<p>
  <strong>Serving:</strong>
  <%= @cookbook.serving %>
</p>

<p>
  <strong>Ingredients:</strong>
  <ul> 
  <% @cookbook.cookbook_ingredients.each do |ci| %>
  <li>
    <%= ci.ingredient.name %>:<%= ci.quantity %>:<%= ci.ingredient.unit %> 
  </li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit, id: :ingredient_unit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.unit %></td>
        <td><%= ingredient.created_at %></td>
        <td><%= ingredient.updated_at %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @ingredient.unit %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Recipe Application</h1>